"use client";

import { ArrowUpRight, Bell, Bot, Camera, Check, ChevronDown, CircleDollarSign, Clock3, FileText, Inbox, LayoutDashboard, Mail, Menu, MoreHorizontal, Plus, Search, Settings, Sparkles, Star, Users, X } from "lucide-react";
import { useState } from "react";

type Deal = { brand: string; initials: string; color: string; campaign: string; amount: string; due: string; status: string; rating: number; workload: number; ease: number; value: number; formats: string[] };

const deals: Deal[] = [
  { brand: "Saie", initials: "S", color: "bg-[#d8a8a5]", campaign: "Summer skin campaign", amount: "$2,400", due: "Reply by today", status: "New offer", rating: 4.8, workload: 3, ease: 5, value: 4, formats: ["9:16 Reel", "3 Stories"] },
  { brand: "Athletic Greens", initials: "AG", color: "bg-[#5e7c62]", campaign: "30-day partnership", amount: "$3,800", due: "Reply by Wed", status: "Negotiating", rating: 4.4, workload: 4, ease: 3, value: 5, formats: ["9:16 Reel", "4:5 Feed"] },
  { brand: "Ritual", initials: "R", color: "bg-[#8d7bab]", campaign: "Creator package launch", amount: "$1,750", due: "Reply by Fri", status: "New offer", rating: 3.9, workload: 2, ease: 4, value: 3, formats: ["4:5 Feed", "1 Story"] },
];

const navItems = [
  { label: "Overview", icon: LayoutDashboard }, { label: "Inbox", icon: Inbox, count: "3" }, { label: "Deals", icon: CircleDollarSign }, { label: "Content", icon: FileText }, { label: "Insights", icon: Camera },
];

function Dots({ value, light = false }: { value: number; light?: boolean }) {
  return <div className="flex gap-1" aria-label={`${value} out of 5`}>{Array.from({ length: 5 }).map((_, index) => <span className={`h-1.5 w-1.5 rounded-full ${index < value ? light ? "bg-white" : "bg-[#1e3428]" : light ? "bg-white/25" : "bg-[#d9ded7]"}`} key={index} />)}</div>;
}

function DealCard({ deal }: { deal: Deal }) {
  return <article className="group rounded-[22px] border border-[#e7ebe4] bg-white p-5 transition duration-200 hover:-translate-y-0.5 hover:border-[#bdcbbd] hover:shadow-[0_14px_32px_rgba(31,57,38,0.08)]">
    <div className="flex items-start justify-between gap-3">
      <div className="flex items-center gap-3"><div className={`flex h-11 w-11 items-center justify-center rounded-2xl ${deal.color} text-sm font-bold text-white shadow-sm`}>{deal.initials}</div><div><h3 className="font-semibold tracking-[-0.02em] text-[#1d2d22]">{deal.brand}</h3><p className="mt-0.5 text-xs text-[#778078]">{deal.campaign}</p></div></div>
      <button className="rounded-lg p-1 text-[#9aa29a] hover:bg-[#f2f5f0] hover:text-[#273b2d]" aria-label={`More options for ${deal.brand}`}><MoreHorizontal size={19} /></button>
    </div>
    <div className="mt-5 flex items-end justify-between border-b border-[#edf0eb] pb-4"><div><p className="text-[11px] font-medium uppercase tracking-[0.13em] text-[#9aa29a]">Offer</p><p className="mt-1 text-2xl font-semibold tracking-[-0.04em] text-[#193322]">{deal.amount}</p></div><span className="rounded-full bg-[#f2f6ef] px-2.5 py-1 text-[11px] font-semibold text-[#527053]">{deal.status}</span></div>
    <div className="mt-4 grid grid-cols-[1fr_auto] gap-x-3 text-xs"><div><div className="flex items-center justify-between text-[#69736a]"><span>Workload</span><span className="font-semibold text-[#25342a]">{deal.workload}/5</span></div><div className="mt-1.5"><Dots value={deal.workload} /></div></div><div className="border-l border-[#edf0eb] pl-4"><p className="text-[#69736a]">Deal rating</p><div className="mt-1 flex items-center gap-1 font-semibold text-[#1b3925]"><Star size={13} fill="currentColor" /> {deal.rating}</div></div></div>
    <div className="mt-4 rounded-xl bg-[#f6f8f4] p-3"><div className="flex items-center justify-between gap-2"><p className="text-[11px] font-semibold uppercase tracking-[0.11em] text-[#6a786d]">Aspect ratio fit</p><span className="text-right text-[10px] font-medium text-[#8a938b]">{deal.formats.join(" · ")}</span></div><div className="mt-2.5 grid grid-cols-2 gap-3"><div className="flex items-center justify-between rounded-lg bg-white px-2.5 py-2"><span className="text-[11px] text-[#69736a]">Creator ease</span><div className="flex items-center gap-1.5"><Dots value={deal.ease} /><b className="text-[11px]">{deal.ease}</b></div></div><div className="flex items-center justify-between rounded-lg bg-white px-2.5 py-2"><span className="text-[11px] text-[#69736a]">Deal value</span><div className="flex items-center gap-1.5"><Dots value={deal.value} /><b className="text-[11px]">{deal.value}</b></div></div></div></div>
    <div className="mt-4 flex items-center justify-between"><span className="flex items-center gap-1.5 text-xs font-medium text-[#a07050]"><Clock3 size={13} /> {deal.due}</span><button className="flex items-center gap-1 text-xs font-semibold text-[#315f3d] hover:text-[#1d4028]">Review deal <ArrowUpRight size={14} /></button></div>
  </article>;
}

export default function Home() {
  const [activeNav, setActiveNav] = useState("Overview");
  const [menuOpen, setMenuOpen] = useState(false);
  const [autoDraft, setAutoDraft] = useState(true);
  return <main className="min-h-screen bg-[#f5f7f3] text-[#203126]">
    {menuOpen && <button aria-label="Close menu" className="fixed inset-0 z-20 bg-[#172d20]/30 lg:hidden" onClick={() => setMenuOpen(false)} />}
    <aside className={`fixed inset-y-0 left-0 z-30 flex w-[252px] flex-col bg-[#193524] px-4 py-5 text-white transition-transform duration-300 lg:translate-x-0 ${menuOpen ? "translate-x-0" : "-translate-x-full"}`}>
      <div className="flex items-center justify-between px-2"><div className="flex items-center gap-2.5"><div className="grid h-8 w-8 place-items-center rounded-xl bg-[#d9f061] text-base font-black text-[#193524]">m</div><span className="text-xl font-semibold tracking-[-0.06em]">manai</span></div><button className="rounded-lg p-1 text-white/70 lg:hidden" onClick={() => setMenuOpen(false)} aria-label="Close navigation"><X size={20} /></button></div>
      <nav className="mt-11 space-y-1"><p className="px-3 pb-2 text-[10px] font-bold uppercase tracking-[0.16em] text-[#a4b6a5]">Workspace</p>{navItems.map(({ label, icon: Icon, count }) => <button key={label} onClick={() => { setActiveNav(label); setMenuOpen(false); }} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm transition ${activeNav === label ? "bg-white/13 font-semibold text-white" : "font-medium text-[#c2d1c4] hover:bg-white/7 hover:text-white"}`}><Icon size={18} strokeWidth={1.9} /><span className="flex-1">{label}</span>{count && <span className="grid h-5 min-w-5 place-items-center rounded-full bg-[#d9f061] px-1 text-[10px] font-bold text-[#193524]">{count}</span>}</button>)}</nav>
      <div className="mt-8 border-t border-white/10 pt-6"><p className="px-3 pb-2 text-[10px] font-bold uppercase tracking-[0.16em] text-[#a4b6a5]">Your account</p><button className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-[#c2d1c4] hover:bg-white/7 hover:text-white"><Users size={18} /> Media kit</button><button className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-[#c2d1c4] hover:bg-white/7 hover:text-white"><Settings size={18} /> Settings</button></div>
      <div className="mt-auto rounded-2xl bg-[#2a4a33] p-3.5"><div className="flex items-center gap-2.5"><div className="grid h-8 w-8 place-items-center rounded-full bg-[#e4be99] text-xs font-bold text-[#5a3828]">AM</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">Avery Morgan</p><p className="text-[11px] text-[#b4c6b6]">Creator plan</p></div><ChevronDown size={15} className="text-[#b4c6b6]" /></div></div>
    </aside>
    <section className="min-h-screen lg:pl-[252px]">
      <header className="flex h-[74px] items-center justify-between border-b border-[#e3e8e0] bg-[#f9faf7] px-5 sm:px-8 lg:px-10"><div className="flex items-center gap-3"><button className="rounded-xl border border-[#e1e6df] bg-white p-2 text-[#36503d] lg:hidden" onClick={() => setMenuOpen(true)} aria-label="Open navigation"><Menu size={19} /></button><div className="hidden h-10 w-[280px] items-center gap-2 rounded-xl border border-[#e4e8e2] bg-white px-3 text-[#8a948b] sm:flex"><Search size={17} /><span className="text-sm">Search deals, brands, emails...</span><span className="ml-auto rounded border border-[#e6e9e4] px-1.5 py-0.5 text-[10px]">⌘ K</span></div></div><div className="flex items-center gap-3"><button className="relative rounded-xl p-2 text-[#5e6d61] hover:bg-[#edf1eb]" aria-label="Notifications"><Bell size={20} /><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-[#dc7c61] ring-2 ring-[#f9faf7]" /></button><div className="h-8 w-px bg-[#e2e6e0]" /><button className="flex items-center gap-2 rounded-xl p-1 pr-2 text-sm font-medium text-[#314937]"><div className="grid h-8 w-8 place-items-center rounded-full bg-[#e4be99] text-[10px] font-bold text-[#5a3828]">AM</div><ChevronDown size={15} /></button></div></header>
      <div className="mx-auto max-w-[1540px] px-5 py-8 sm:px-8 lg:px-10 lg:py-10">
        <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold text-[#738178]"><span className="h-2 w-2 rounded-full bg-[#8bbf76]" /> MONDAY, JUNE 24</div><h1 className="text-3xl font-semibold tracking-[-0.055em] text-[#183122] sm:text-[34px]">Good morning, Avery.</h1><p className="mt-2 text-sm text-[#707c72]">You have <span className="font-semibold text-[#315f3d]">3 new brand offers</span> worth a closer look.</p></div><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#1d422b] px-4 py-3 text-sm font-semibold text-white shadow-[0_7px_18px_rgba(26,64,42,0.18)] hover:bg-[#153720]"><Plus size={17} /> Add a deal</button></div>
        <div className="mt-7 grid gap-5 xl:grid-cols-[minmax(0,1fr)_318px]"><div className="space-y-5">
          <section className="overflow-hidden rounded-[22px] bg-[#1d422b] text-white shadow-[0_14px_30px_rgba(27,65,42,0.16)]"><div className="relative overflow-hidden px-6 py-6 sm:px-7"><div className="absolute -right-16 -top-24 h-52 w-52 rounded-full border-[26px] border-[#d9f061]/15" /><div className="relative flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.13em] text-[#c7d6c8]"><Sparkles size={15} className="text-[#d9f061]" /> Your AI manager</div><h2 className="mt-2 text-xl font-semibold tracking-[-0.035em]">Your inbox is beautifully handled.</h2><p className="mt-1 max-w-xl text-sm leading-6 text-[#c7d6c8]">I found 3 offers, prepared 2 reply drafts, and spotted one deadline that needs your attention.</p></div><button className="shrink-0 rounded-xl bg-[#d9f061] px-4 py-2.5 text-sm font-bold text-[#1d422b] hover:bg-[#e4f77e]">Open inbox</button></div></div><div className="grid border-t border-white/10 bg-black/10 sm:grid-cols-3">{[{ value: "3", label: "new offers" }, { value: "$7,950", label: "potential revenue" }, { value: "2", label: "drafts ready" }].map((stat) => <div className="border-b border-white/10 px-6 py-3.5 last:border-0 sm:border-b-0 sm:border-r sm:last:border-r-0" key={stat.label}><span className="text-lg font-semibold tracking-[-0.04em]">{stat.value}</span><span className="ml-2 text-xs text-[#b9cab9]">{stat.label}</span></div>)}</div></section>
          <section><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-semibold tracking-[-0.035em] text-[#203426]">Top opportunities</h2><p className="mt-0.5 text-xs text-[#788178]">Rated by pay, workload, deadlines, and content fit.</p></div><button className="text-sm font-semibold text-[#3e7248] hover:text-[#234d2e]">View all deals</button></div><div className="grid gap-4 md:grid-cols-2 2xl:grid-cols-3">{deals.map((deal) => <DealCard deal={deal} key={deal.brand} />)}</div></section>
        </div><div className="space-y-5">
          <section className="rounded-[22px] border border-[#e3e8e1] bg-white p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><div className="grid h-8 w-8 place-items-center rounded-lg bg-[#f3eaf8] text-[#9c56ae]"><Camera size={16} /></div><h2 className="font-semibold tracking-[-0.02em] text-[#223426]">Instagram pulse</h2></div><button className="text-xs font-semibold text-[#48744f]">View insights</button></div><div className="mt-5 flex items-end gap-4"><p className="text-3xl font-semibold tracking-[-0.06em] text-[#1c3524]">124.8k</p><span className="mb-1.5 rounded-full bg-[#edf6e9] px-2 py-0.5 text-[10px] font-bold text-[#55904e]">+8.4%</span></div><p className="mt-1 text-xs text-[#758076]">Followers · last 30 days</p><div className="mt-5 flex h-16 items-end gap-1.5">{[31,44,37,54,40,61,48,75,58,87,64,93,72,80].map((height, i) => <div key={i} style={{ height: `${height}%` }} className={`flex-1 rounded-t-sm ${i === 11 ? "bg-[#b7d85f]" : "bg-[#d9e7d3]"}`} />)}</div><div className="mt-3 flex justify-between text-[10px] font-medium text-[#98a198]"><span>May 25</span><span>Jun 24</span></div></section>
          <section className="rounded-[22px] border border-[#e3e8e1] bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold tracking-[-0.02em] text-[#223426]">Email autopilot</h2><p className="mt-0.5 text-xs text-[#7e887e]">Drafts always need your approval.</p></div><button onClick={() => setAutoDraft(!autoDraft)} className={`relative h-6 w-11 rounded-full transition ${autoDraft ? "bg-[#74a85b]" : "bg-[#cfd6cf]"}`} aria-label="Toggle automatic drafting"><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow transition ${autoDraft ? "left-6" : "left-1"}`} /></button></div><div className="mt-5 space-y-3"><div className="flex items-center gap-3 rounded-xl bg-[#f7f9f5] p-3"><div className="grid h-8 w-8 place-items-center rounded-full bg-[#fff3df] text-[#d7973f]"><Mail size={15} /></div><div className="flex-1"><p className="text-xs font-semibold text-[#304134]">2 replies ready</p><p className="text-[11px] text-[#7c877e]">Waiting for your approval</p></div><ArrowUpRight size={15} className="text-[#6d886f]" /></div><div className="flex items-center gap-3 rounded-xl bg-[#f7f9f5] p-3"><div className="grid h-8 w-8 place-items-center rounded-full bg-[#eef3ff] text-[#6580c0]"><Check size={15} /></div><div className="flex-1"><p className="text-xs font-semibold text-[#304134]">14 emails organized</p><p className="text-[11px] text-[#7c877e]">This week</p></div></div></div></section>
          <section className="rounded-[22px] border border-[#e3e8e1] bg-[#fffdf9] p-5"><div className="flex items-start gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[#fff1d9] text-[#c78530]"><Bot size={18} /></div><div><p className="text-sm font-semibold tracking-[-0.02em] text-[#45331f]">Manager note</p><p className="mt-1 text-xs leading-5 text-[#826e55]">Saie&apos;s offer is a strong fit for your audience and your preferred 9:16 workflow.</p><button className="mt-2 text-xs font-semibold text-[#a26928]">See why it scored 4.8 <ArrowUpRight className="inline" size={12} /></button></div></div></section>
        </div></div>
      </div>
    </section>
  </main>;
}
