"use client";

import { ArrowRight, Eye, EyeOff, LockKeyhole, Mail, Sparkles } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";

export default function SignInPage() {
  const router = useRouter();
  const [showPassword, setShowPassword] = useState(false);

  return <main className="min-h-screen overflow-hidden bg-[#121117] text-white">
    <div className="pointer-events-none fixed inset-0 overflow-hidden"><div className="animate-float absolute -left-24 top-16 h-72 w-72 rounded-full bg-[#6f42ad]/25 blur-3xl" /><div className="absolute -right-20 bottom-0 h-80 w-80 rounded-full bg-[#a779e4]/15 blur-3xl" /></div>
    <div className="relative mx-auto flex min-h-screen max-w-7xl items-center justify-center px-5 py-10 lg:grid lg:grid-cols-[1.1fr_0.9fr] lg:gap-20 lg:px-12">
      <section className="hidden lg:block"><div className="flex items-center gap-2.5"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-[#c7a6ff] text-xl font-black text-[#241633]">m</div><span className="text-2xl font-semibold tracking-[-0.06em]">manai</span></div><div className="mt-20 max-w-xl"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.15em] text-[#c7a6ff]"><Sparkles size={15} /> Your creator business manager</p><h1 className="mt-5 text-5xl font-semibold leading-[1.03] tracking-[-0.065em] text-[#f5f0fb]">Let your best work be the work only you can do.</h1><p className="mt-6 max-w-md text-lg leading-8 text-[#bfb4cd]">MANAI handles the moving pieces behind your brand partnerships—so you can focus on creating.</p></div><div className="mt-12 flex items-center gap-3 text-sm text-[#c8bdd5]"><span className="grid h-7 w-7 place-items-center rounded-full bg-[#302546] text-[#c7a6ff]">✓</span> Built for creators who run their own business</div></section>
      <section className="animate-fade-up w-full max-w-md rounded-[28px] border border-[#3a2c4d] bg-[#201c28]/95 p-6 shadow-[0_24px_80px_rgba(0,0,0,0.35)] sm:p-8"><div className="flex items-center gap-2.5 lg:hidden"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#c7a6ff] text-lg font-black text-[#241633]">m</div><span className="text-xl font-semibold tracking-[-0.06em]">manai</span></div><div className="mt-8"><p className="text-sm font-medium text-[#c7a6ff]">Welcome back</p><h2 className="mt-2 text-3xl font-semibold tracking-[-0.055em]">Sign in to MANAI</h2><p className="mt-2 text-sm text-[#a99eb8]">Your deals, inbox, and insights are waiting.</p></div><form className="mt-7 space-y-4" onSubmit={(event) => { event.preventDefault(); router.push("/onboarding"); }}><label className="block text-sm font-medium text-[#ded5e9]">Email address<div className="relative mt-2"><Mail className="pointer-events-none absolute left-3 top-3 text-[#9588a5]" size={17} /><input required type="email" placeholder="you@example.com" className="w-full rounded-xl border border-[#463756] bg-[#15121b] py-3 pl-10 pr-3 text-sm text-white outline-none placeholder:text-[#7f738d] focus:border-[#c7a6ff]" /></div></label><label className="block text-sm font-medium text-[#ded5e9]">Password<div className="relative mt-2"><LockKeyhole className="pointer-events-none absolute left-3 top-3 text-[#9588a5]" size={17} /><input required type={showPassword ? "text" : "password"} placeholder="Enter your password" className="w-full rounded-xl border border-[#463756] bg-[#15121b] py-3 pl-10 pr-11 text-sm text-white outline-none placeholder:text-[#7f738d] focus:border-[#c7a6ff]" /><button type="button" onClick={() => setShowPassword(!showPassword)} className="absolute right-3 top-3 text-[#9588a5]" aria-label="Show password">{showPassword ? <EyeOff size={17} /> : <Eye size={17} />}</button></div></label><div className="flex justify-end"><button type="button" className="text-xs font-semibold text-[#c7a6ff] hover:text-[#ddceff]">Forgot password?</button></div><button className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#c7a6ff] py-3.5 text-sm font-bold text-[#251735] transition hover:-translate-y-0.5 hover:bg-[#ddcaff]">Continue <ArrowRight size={17} /></button></form><div className="my-6 flex items-center gap-3 text-xs text-[#756a82]"><div className="h-px flex-1 bg-[#3a2e48]" /> OR <div className="h-px flex-1 bg-[#3a2e48]" /></div><button className="flex w-full items-center justify-center gap-2 rounded-xl border border-[#463756] bg-[#282132] py-3 text-sm font-semibold text-[#eee8f5] transition hover:bg-[#31283e]"><span className="grid h-5 w-5 place-items-center rounded-full bg-white text-[10px] font-bold text-[#5340a3]">G</span> Continue with Google</button><p className="mt-7 text-center text-sm text-[#a99eb8]">New to MANAI? <Link className="font-semibold text-[#c7a6ff] hover:text-[#ddceff]" href="/onboarding">Create an account</Link></p></section>
    </div>
  </main>;
}
