"use client";

import { ArrowRight, BadgeCheck, Building2, Mail, ShieldCheck, Sparkles } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";

export default function OnboardingPage() {
  const router = useRouter();
  return <main className="min-h-screen bg-[#121117] px-5 py-8 text-white sm:px-8"><header className="mx-auto flex max-w-5xl items-center justify-between"><Link href="/" className="flex items-center gap-2.5"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#c7a6ff] text-lg font-black text-[#241633]">m</div><span className="text-xl font-semibold tracking-[-0.06em]">manai</span></Link><span className="text-sm text-[#a99eb8]">Step 1 of 2</span></header><div className="mx-auto mt-8 max-w-5xl"><div className="h-1.5 overflow-hidden rounded-full bg-[#30263d]"><div className="h-full w-1/2 rounded-full bg-[#c7a6ff]" /></div></div><section className="animate-fade-up mx-auto mt-12 max-w-xl"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#332247] text-[#c7a6ff]"><Building2 size={22} /></div><p className="mt-7 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.15em] text-[#c7a6ff]"><Sparkles size={14} /> Set up your workspace</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.06em] text-[#f5f0fb]">Add your business email.</h1><p className="mt-4 text-base leading-7 text-[#b8adC5]">This is the professional inbox MANAI will organize for your brand opportunities. You stay in control of access and every action.</p><form className="mt-8 rounded-[24px] border border-[#3d304d] bg-[#201c28] p-5 sm:p-6" onSubmit={(event) => { event.preventDefault(); router.push("/plans"); }}><label className="block text-sm font-semibold text-[#e5ddef]">Business email<div className="relative mt-2"><Mail className="pointer-events-none absolute left-3 top-3 text-[#9a8ca9]" size={18} /><input required type="email" placeholder="hello@yourbrand.com" className="w-full rounded-xl border border-[#493957] bg-[#15121b] py-3.5 pl-11 pr-3 text-sm text-white outline-none placeholder:text-[#7f738d] focus:border-[#c7a6ff]" /></div></label><div className="mt-5 space-y-3"><div className="flex gap-3 rounded-xl bg-[#292135] p-3"><ShieldCheck className="mt-0.5 shrink-0 text-[#c7a6ff]" size={18} /><p className="text-xs leading-5 text-[#c6bad4]">Your inbox is connected securely. MANAI never sends or accepts a deal without the permission included in your plan.</p></div><div className="flex gap-3 rounded-xl bg-[#292135] p-3"><BadgeCheck className="mt-0.5 shrink-0 text-[#c7a6ff]" size={18} /><p className="text-xs leading-5 text-[#c6bad4]">You can revoke access whenever you want from Settings.</p></div></div><button className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-[#c7a6ff] py-3.5 text-sm font-bold text-[#251735] transition hover:-translate-y-0.5 hover:bg-[#ddcaff]">Choose your plan <ArrowRight size={17} /></button></form></section></main>;
}
